{
 "title": "Données en temps réels",
 "description": "Dashboard de consultation des données en temps réels",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Accidents",
   "type": "table",
   "description": "Liste des accidents",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "CONTROLE_TRAFFIC",
     "rawSql": "SELECT * FROM CONTROLE_TRAFFIC.TRAFFIC_EVENT WHERE type = 'accident' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Embouteillages",
   "type": "table",
   "description": "Liste des embouteillages",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "CONTROLE_TRAFFIC",
     "rawSql": "SELECT * FROM CONTROLE_TRAFFIC.TRAFFIC_EVENT WHERE type = 'embouteillage' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Données périodique",
   "type": "table",
   "description": "Liste des données périodiques",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "CONTROLE_TRAFFIC",
     "rawSql": "SELECT * FROM CONTROLE_TRAFFIC.CAR_EVENT ORDER BY id DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Données ponctuelle",
   "type": "table",
   "description": "Liste des données ponctuelle",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "CONTROLE_TRAFFIC",
     "rawSql": "SELECT * FROM CONTROLE_TRAFFIC.TRAFFIC_EVENT LIMIT 50 "
    }
   ]
  }
 ]
}