{
 "title": "Statistiques2",
 "time": { "from": "2022-08-31T16:00:49.906Z", "to": "2022-09-06T07:58:34.359Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Vitesse moyenne",
   "type": "timeseries",
   "description": "Vitesse moyenne des usagers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "CONTROLE_TRAFFIC",
     "rawSql": "SELECT AVG(vitesse) AS \"Vitesse moyenne\", timestamp_record FROM CONTROLE_TRAFFIC.CAR_EVENT GROUP BY timestamp_record LIMIT 50 "
    }
   ]
  },
  {
   "title": "Evolution des occurences d'accidents",
   "type": "timeseries",
   "description": "Visualisation de l'evolution des accidents",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "CONTROLE_TRAFFIC",
     "rawSql": "SELECT COUNT(id) AS \"nb_embouteillages\", timestamp_occur FROM CONTROLE_TRAFFIC.TRAFFIC_EVENT WHERE type = 'accident' GROUP BY timestamp_occur ORDER BY timestamp_occur DESC "
    }
   ]
  },
  {
   "title": "Evolution des embouteillages",
   "type": "timeseries",
   "description": "Visualisation de l'evolution des embouteillages",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "CONTROLE_TRAFFIC",
     "rawSql": "SELECT COUNT(id) AS \"nb_embouteillages\", timestamp_occur FROM CONTROLE_TRAFFIC.TRAFFIC_EVENT WHERE type = 'embouteillage' GROUP BY timestamp_occur ORDER BY timestamp_occur DESC "
    }
   ]
  },
  {
   "title": "Carte des accidents et embouteillages",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "CONTROLE_TRAFFIC",
     "rawSql": "SELECT geo_lat AS \"lat\", geo_lon AS \"lon\" FROM CONTROLE_TRAFFIC.TRAFFIC_EVENT WHERE type = 'accident' LIMIT 50 "
    },
    {
     "dataset": "CONTROLE_TRAFFIC",
     "rawSql": "SELECT geo_lat AS \"lat\", geo_lon AS \"lon\" FROM CONTROLE_TRAFFIC.TRAFFIC_EVENT WHERE type = 'embouteillage' LIMIT 50 "
    }
   ]
  }
 ]
}